export { default as StructureHero } from './StructureHero'
export { default as StructureKpis } from './StructureKpis'
export { default as PublicationsChart } from './PublicationsChart'
export { default as MembersTable } from './MembersTable'
export { default as SidebarIdentifiers } from './SidebarIdentifiers'
export { default as SidebarAbout } from './SidebarAbout'
export { default as SidebarDisciplines } from './SidebarDisciplines'
export { default as SidebarSources } from './SidebarSources'
export { default as SubstructuresTable } from './SubstructuresTable'
export { default as SidebarMemberships } from './SidebarMemberships'
export { MembresTab, EquipesTab, PublicationsTab, AProposTab } from './TabsUnitContent'
